### PR TITLE
Add Java 8 Support

### PR DESCRIPTION
**Pull request by Glavo**

### CODE REVIEW

**Comment by Glavo** [comment]
@tonsky

**Comment by tonsky** [comment]
Should we separate module-info.java into java9 source tree? Like this https://github.com/HumbleUI/Types/commit/d1cd9d267db3cc5d1aa4f4ccc149096cca863e55?

**Comment by Glavo** [comment]
> Should we separate module-info.java into java9 source tree? Like this [d1cd9d2](https://github.com/HumbleUI/Types/commit/d1cd9d267db3cc5d1aa4f4ccc149096cca863e55)?

I'm sure it's not a problem.

**Comment by tonsky** [comment]
Thanks! Merged and published as 0.2.0

**Pull request closed without merging**
